// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaskoFy.DataAccess;

#nullable disable

namespace StaskoFy.DataAccess.Migrations
{
    [DbContext(typeof(StaskoFyDbContext))]
    [Migration("20260116130045_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("SongsCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-album-cover-art.png",
                            Length = new TimeSpan(0, 1, 5, 0, 0),
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            SongsCount = 5,
                            Title = "A Great Chaos (Deluxe)"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-album-cover-art.png",
                            Length = new TimeSpan(0, 0, 40, 49, 0),
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            SongsCount = 6,
                            Title = "Super Slimey"
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-album-cover-art.png",
                            Length = new TimeSpan(0, 0, 36, 25, 0),
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            SongsCount = 4,
                            Title = "Pray For Paris"
                        },
                        new
                        {
                            Id = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-album-cover-art.png",
                            Length = new TimeSpan(0, 1, 17, 0, 0),
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            SongsCount = 6,
                            Title = "CALL ME IF YOU GET LOST: The Estate Sale"
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-album-cover-art.png",
                            Length = new TimeSpan(0, 1, 1, 0, 0),
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            SongsCount = 4,
                            Title = "XTENDED"
                        },
                        new
                        {
                            Id = new Guid("61111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-album-cover-art.png",
                            Length = new TimeSpan(0, 0, 54, 32, 0),
                            ReleaseDate = new DateOnly(2025, 9, 22),
                            SongsCount = 6,
                            Title = "ᐸ/3³"
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("41111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("05111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("61111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("71111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("81111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("08111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("91111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("09111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("10111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistAlbum", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("ArtistsAlbums");

                    b.HasData(
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistSong", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistsSongs");

                    b.HasData(
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("05111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("10111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("09111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("12111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("14111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("15111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("16111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("17111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("18111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("19111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("21111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("25111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("26111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("28111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("22111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("25111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("91111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("16111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("91111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("24111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("71111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("81111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("10111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Hip-Hop"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            Name = "Mumble Rap"
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            Name = "Trap"
                        },
                        new
                        {
                            Id = new Guid("41111111-1111-1111-1111-111111111111"),
                            Name = "Hypertrap"
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            Name = "Boom Bap"
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.LikedSongs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedSongs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 6),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 8),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 8),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 9, 16),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2025, 1, 30),
                            SongId = new Guid("10111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2023, 12, 5),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 4, 16),
                            SongId = new Guid("05111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 8),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 3, 8),
                            SongId = new Guid("19111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 9, 16),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 9, 16),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 11, 26),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2023, 1, 29),
                            SongId = new Guid("14111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("14111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2025, 12, 29),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("15111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2025, 12, 22),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("16111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2023, 10, 29),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataCreated")
                        .HasColumnType("date");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("SongCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataCreated = new DateOnly(2024, 12, 4),
                            ImageURL = "/wwwroot/images/defaults/default_album_cover.png",
                            IsPublic = true,
                            Length = new TimeSpan(0, 0, 16, 59, 0),
                            SongCount = 6,
                            Title = "Hip-Hop & Trap Filmar",
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            DataCreated = new DateOnly(2024, 12, 10),
                            ImageURL = "/wwwroot/images/defaults/default_album_cover.png",
                            IsPublic = true,
                            Length = new TimeSpan(0, 0, 19, 9, 0),
                            SongCount = 7,
                            Title = "00PIUMxx Filmar",
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            DataCreated = new DateOnly(2022, 6, 27),
                            ImageURL = "/wwwroot/images/defaults/default_album_cover.png",
                            IsPublic = false,
                            Length = new TimeSpan(0, 0, 22, 29, 0),
                            SongCount = 8,
                            Title = "Mnooo Cherno",
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.PlaylistSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistsSongs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 12, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 11, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 10, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("10111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 9, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 8, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 7, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("15111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 6, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 5, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 4, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("05111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 3, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 2, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("26111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 1, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 12, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("28111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("14111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 11, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("15111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("15111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 10, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("16111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 9, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("16111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("17111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 8, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("18111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 7, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("19111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 6, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("14111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 5, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("22111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 4, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("24111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 8, 0),
                            Likes = 10044245,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Green Room"
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 20, 0),
                            Likes = 643545,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Lose It"
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 54, 0),
                            Likes = 234566,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Me N My Kup"
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 7, 0),
                            Likes = 8384754,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Paranoid"
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 4, 0),
                            Likes = 3647835,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "ss"
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 24, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "No Cap"
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 24, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "All da Smoke"
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 26, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "200"
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 46, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "Cruise Ship"
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 46, 0),
                            Likes = 235678,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "Feed Me Dope"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 40, 0),
                            Likes = 98765,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "Killed Before"
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 1, 35, 0),
                            Likes = 123456,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "No Vacancy"
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 5, 49, 0),
                            Likes = 654321,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "327"
                        },
                        new
                        {
                            Id = new Guid("14111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 1, 49, 0),
                            Likes = 234567,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "Euro Step"
                        },
                        new
                        {
                            Id = new Guid("15111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 4, 0),
                            Likes = 345678,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "Versace"
                        },
                        new
                        {
                            Id = new Guid("16111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 35, 0),
                            Likes = 456789,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "HOT WIND BLOWS"
                        },
                        new
                        {
                            Id = new Guid("17111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 8, 35, 0),
                            Likes = 567890,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "WILSHIRE"
                        },
                        new
                        {
                            Id = new Guid("18111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 57, 0),
                            Likes = 678901,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "SAFARI"
                        },
                        new
                        {
                            Id = new Guid("19111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 36, 0),
                            Likes = 789012,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "WHAT A DAY"
                        },
                        new
                        {
                            Id = new Guid("20111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 41, 0),
                            Likes = 890123,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "DOGTOOTH"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 50, 0),
                            Likes = 901234,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "HEAVEN TO ME"
                        },
                        new
                        {
                            Id = new Guid("22111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 20, 0),
                            Likes = 12345,
                            ReleaseDate = new DateOnly(2019, 7, 30),
                            Title = "Bane"
                        },
                        new
                        {
                            Id = new Guid("23111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 14, 0),
                            Likes = 23456,
                            ReleaseDate = new DateOnly(2023, 3, 3),
                            Title = "if looks could kill"
                        },
                        new
                        {
                            Id = new Guid("24111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 4, 46, 0),
                            Likes = 34567,
                            ReleaseDate = new DateOnly(2023, 9, 1),
                            Title = "Kat Food"
                        },
                        new
                        {
                            Id = new Guid("25111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 48, 0),
                            Likes = 45678,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "MDMA"
                        },
                        new
                        {
                            Id = new Guid("26111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 18, 0),
                            Likes = 78901,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "Freestyle 2"
                        },
                        new
                        {
                            Id = new Guid("27111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 2, 45, 0),
                            Likes = 56789,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "Delinquent"
                        },
                        new
                        {
                            Id = new Guid("28111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/wwwroot/images/defaults/default-song-cover-art.png",
                            Length = new TimeSpan(0, 0, 3, 21, 0),
                            Likes = 67890,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "Fashion Habits"
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8fad0d6-07eb-4351-89f2-01c05e8d0efb",
                            Email = "kenCarson@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "kenCarson@gmail.com",
                            NormalizedUserName = "kenCarson",
                            PasswordHash = "AQAAAAIAAYagAAAAEMCQLcAIPG2V534FN4zOvwTsY+yqy0vqMhHzfOXy+biQmpvFrF+VjIWU3JMycLzTKA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "kenCarson"
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2464e55b-6649-43df-a9fc-e11282cba159",
                            Email = "future@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "future@gmail.com",
                            NormalizedUserName = "future",
                            PasswordHash = "AQAAAAIAAYagAAAAEDTwD8DDJoZ5M+E2xrkKJluvRNRA0eWKLxkQAiF3SIkx74yjnXOdGGst5K4K7ufXTw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "future"
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "60e81486-52aa-4bb4-afa2-678b4c4b7f09",
                            Email = "youngThug@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "youngThug@gmail.com",
                            NormalizedUserName = "youngThug",
                            PasswordHash = "AQAAAAIAAYagAAAAEMf53InG1thALVUnjM2MfrqwvbJj8SSk1lREnwMzF1AFaS1OekK1JZyEVDde9dl1KA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "youngThug"
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b6cef5c-9c7e-4add-9312-87c0edc15553",
                            Email = "westsideGunn@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "westsideGunn@gmail.com",
                            NormalizedUserName = "westsideGunn",
                            PasswordHash = "AQAAAAIAAYagAAAAELfuuUGxI66glUG0CdIe9sNu08L63BxAMTok6WBZiAcD3nexKKi0zNHHkT7B7ybmGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "westsideGunn"
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "53d9903c-3381-4422-bf37-527728fa320b",
                            Email = "tylerTheCreator@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "tylerTheCreator@gmail.com",
                            NormalizedUserName = "tylerTheCreator",
                            PasswordHash = "AQAAAAIAAYagAAAAEAp37uuMqZbRr95ngfh/SZ+BYvLUS5JWD09sGqb854utN5jGCbiBHsPdSTZ8M4m3CA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "05111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "tylerTheCreator"
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14cd42e4-4ae3-4801-abaf-2bc1b894baa5",
                            Email = "destroyLonely@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "destroyLonely@gmail.com",
                            NormalizedUserName = "destroyLonely",
                            PasswordHash = "AQAAAAIAAYagAAAAEK4lUILXQ6pZPPFLjRbejhBP6nl2ktUSE68MkBpqZCrLvqDTSo5GtPHcduBlJP9/pQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "destroyLonely"
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b5d1d35a-f83a-4982-91d1-ca8a8acc3e7c",
                            Email = "joeyBada$$@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "joeyBada$$@gmail.com",
                            NormalizedUserName = "joeyBada$$",
                            PasswordHash = "AQAAAAIAAYagAAAAECBwqvcsyuLnj4g01HBW51F0MK/xKvSz2Bibwc4jzhUJT7YVgw0uXoc+cIw0pRsVFQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "07111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "joeyBada$$"
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14b5d263-1022-4e9e-bc96-3180baf21555",
                            Email = "billiEssco@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "billiEssco@gmail.com",
                            NormalizedUserName = "billiEssco",
                            PasswordHash = "AQAAAAIAAYagAAAAENXjVDHeG23yUhS8tz3lg4+iVo0kogrSKeg3Q9e+VkntMviQRjaGquqUtqS8Jsa25Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "08111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "billiEssco"
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0c79c560-7bcd-4998-90aa-561f7a8e3710",
                            Email = "lilWayne@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "lilWayne@gmail.com",
                            NormalizedUserName = "lilWayne",
                            PasswordHash = "AQAAAAIAAYagAAAAEArT88fhPxiEk0fHsCk5MBuPqZMGiwZRpzS396WiUfJcjfWDZCFl+8xHGRKQR7CoMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "09111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "lilWayne"
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db07f996-6b16-4f03-ba7f-27a885649ac0",
                            Email = "homixideGang@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "homixideGang@gmail.com",
                            NormalizedUserName = "homixideGang",
                            PasswordHash = "AQAAAAIAAYagAAAAEGpbK3DNt9DCVM0zdOsF8f/wpqu5Fmzu6UCt9vBXDvmHOQL4XNUSFejnU4K3+s4tiQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "homixideGang"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b914d59e-86e0-483e-8ed8-e7cbfc609437",
                            Email = "stdimov2007@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "stdimov2007@gmail.com",
                            NormalizedUserName = "stasko456",
                            PasswordHash = "AQAAAAIAAYagAAAAELjtGitDhoryjGrbCACTaW6f4Q6qjyraoTnAo2NY/nzZjT5x+Xv8CAvg+9ri+Iv4MQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "11111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "stasko456"
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1abb4043-bde4-42e1-982a-08d027c1d9fc",
                            Email = "simon2403e8@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "simon2403e8@gmail.com",
                            NormalizedUserName = "simon333",
                            PasswordHash = "AQAAAAIAAYagAAAAEK1yE0XxN/TfWXDRLW2giXcDlbcpXhNpKiJkOtodf7Uh9tT1vRppa0X34TIz/cxFnQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "simon333"
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73524820-b4d5-4671-8cc7-e367b9cb2199",
                            Email = "nikolaPeew@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/wwwroot/images/defaults/default-user-pfp.png",
                            LockoutEnabled = false,
                            NormalizedEmail = "nikolaPeew@gmail.com",
                            NormalizedUserName = "n_peew07",
                            PasswordHash = "AQAAAAIAAYagAAAAEJUKBXy5HRyK11s4mUDbJLi8rQ0AomnyRYhnVPvaCv3vUv6gj59XWi0CjY1dKv1TSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "n_peew07"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Artist", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistAlbum", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Album", "Album")
                        .WithMany("ArtistsAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.Artist", "Artist")
                        .WithMany("ArtistsAlbums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistSong", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Artist", "Artist")
                        .WithMany("ArtistsSongs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.Song", "Song")
                        .WithMany("ArtistsSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.LikedSongs", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.User", "User")
                        .WithMany("LikedSongs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Playlist", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.PlaylistSong", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistsSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Song", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId");

                    b.HasOne("StaskoFy.Models.Entities.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Album", b =>
                {
                    b.Navigation("ArtistsAlbums");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Artist", b =>
                {
                    b.Navigation("ArtistsAlbums");

                    b.Navigation("ArtistsSongs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistsSongs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Song", b =>
                {
                    b.Navigation("ArtistsSongs");

                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.User", b =>
                {
                    b.Navigation("LikedSongs");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
