// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaskoFy.DataAccess;

#nullable disable

namespace StaskoFy.DataAccess.Migrations
{
    [DbContext(typeof(StaskoFyDbContext))]
    partial class StaskoFyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("SongsCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/a_great_chaos_deluxe.jpg",
                            Length = new TimeSpan(0, 1, 5, 0, 0),
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            SongsCount = 5,
                            Title = "A Great Chaos (Deluxe)"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/super_slimey.jpg",
                            Length = new TimeSpan(0, 0, 40, 49, 0),
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            SongsCount = 6,
                            Title = "Super Slimey"
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/pray_for_paris.jpg",
                            Length = new TimeSpan(0, 0, 36, 25, 0),
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            SongsCount = 4,
                            Title = "Pray For Paris"
                        },
                        new
                        {
                            Id = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/call_me_if_you_get_lost_the_estate_sale.jpg",
                            Length = new TimeSpan(0, 1, 17, 0, 0),
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            SongsCount = 6,
                            Title = "CALL ME IF YOU GET LOST: The Estate Sale"
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/xtended.jpg",
                            Length = new TimeSpan(0, 1, 1, 0, 0),
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            SongsCount = 4,
                            Title = "XTENDED"
                        },
                        new
                        {
                            Id = new Guid("61111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/broken_hearts_3.jpg",
                            Length = new TimeSpan(0, 0, 54, 32, 0),
                            ReleaseDate = new DateOnly(2025, 9, 22),
                            SongsCount = 6,
                            Title = "ᐸ/3³"
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("41111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("05111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("61111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("71111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("81111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("08111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("91111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("09111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("10111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistAlbum", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("ArtistsAlbums");

                    b.HasData(
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistSong", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistsSongs");

                    b.HasData(
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("05111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("10111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("09111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("12111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("14111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("41111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("15111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("16111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("17111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("18111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("19111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("51111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("21111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("25111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("26111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("28111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("22111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("61111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("25111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("91111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("16111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("91111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("24111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("71111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("81111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("13111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ArtistId = new Guid("10111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Hip-Hop"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            Name = "Mumble Rap"
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            Name = "Trap"
                        },
                        new
                        {
                            Id = new Guid("41111111-1111-1111-1111-111111111111"),
                            Name = "Hypertrap"
                        },
                        new
                        {
                            Id = new Guid("51111111-1111-1111-1111-111111111111"),
                            Name = "Boom Bap"
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.LikedSongs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedSongs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 6),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 8),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 8),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 9, 16),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2025, 1, 30),
                            SongId = new Guid("10111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2023, 12, 5),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 4, 16),
                            SongId = new Guid("05111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 7, 8),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 3, 8),
                            SongId = new Guid("19111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 9, 16),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 9, 16),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2024, 11, 26),
                            SongId = new Guid("01111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2023, 1, 29),
                            SongId = new Guid("14111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("14111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2025, 12, 29),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("15111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2025, 12, 22),
                            SongId = new Guid("08111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("16111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2023, 10, 29),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("SongCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateCreated = new DateOnly(2024, 12, 4),
                            ImageURL = "/images/playlists-art-covers/hip-hop-trap-filmar.jpg",
                            IsPublic = true,
                            Length = new TimeSpan(0, 0, 16, 59, 0),
                            SongCount = 6,
                            Title = "Hip-Hop & Trap Filmar",
                            UserId = new Guid("01111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            DateCreated = new DateOnly(2024, 12, 10),
                            ImageURL = "/images/playlists-art-covers/opium_filmar.jpg",
                            IsPublic = true,
                            Length = new TimeSpan(0, 0, 19, 9, 0),
                            SongCount = 7,
                            Title = "00PIUM Filmar",
                            UserId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("31111111-1111-1111-1111-111111111111"),
                            DateCreated = new DateOnly(2022, 6, 27),
                            ImageURL = "/images/playlists-art-covers/mnooo_cherno.jpg",
                            IsPublic = false,
                            Length = new TimeSpan(0, 0, 22, 29, 0),
                            SongCount = 8,
                            Title = "Mnooo Cherno",
                            UserId = new Guid("03111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.PlaylistSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistsSongs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 12, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("06111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 11, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("07111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 10, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("10111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 9, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 8, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 7, 3),
                            PlaylistId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("15111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 6, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 5, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("04111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 4, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("05111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 3, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("23111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 2, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("26111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2007, 1, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("27111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 12, 3),
                            PlaylistId = new Guid("21111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("28111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("14111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 11, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("15111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("15111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 10, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("20111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("16111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 9, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("16111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("17111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 8, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("02111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("18111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 7, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("03111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("19111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 6, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("14111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("20111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 5, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("22111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            DateAdded = new DateOnly(2006, 4, 3),
                            PlaylistId = new Guid("31111111-1111-1111-1111-111111111111"),
                            SongId = new Guid("24111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/a_great_chaos_deluxe.jpg",
                            Length = new TimeSpan(0, 0, 3, 8, 0),
                            Likes = 10044245,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Green Room"
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/a_great_chaos_deluxe.jpg",
                            Length = new TimeSpan(0, 0, 2, 20, 0),
                            Likes = 643545,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Lose It"
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/a_great_chaos_deluxe.jpg",
                            Length = new TimeSpan(0, 0, 3, 54, 0),
                            Likes = 234566,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Me N My Kup"
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/a_great_chaos_deluxe.jpg",
                            Length = new TimeSpan(0, 0, 2, 7, 0),
                            Likes = 8384754,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "Paranoid"
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/a_great_chaos_deluxe.jpg",
                            Length = new TimeSpan(0, 0, 3, 4, 0),
                            Likes = 3647835,
                            ReleaseDate = new DateOnly(2024, 7, 5),
                            Title = "ss"
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/super_slimey.jpg",
                            Length = new TimeSpan(0, 0, 2, 24, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "No Cap"
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/super_slimey.jpg",
                            Length = new TimeSpan(0, 0, 3, 24, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "All da Smoke"
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/super_slimey.jpg",
                            Length = new TimeSpan(0, 0, 2, 26, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "200"
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/super_slimey.jpg",
                            Length = new TimeSpan(0, 0, 2, 46, 0),
                            Likes = 125467,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "Cruise Ship"
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/super_slimey.jpg",
                            Length = new TimeSpan(0, 0, 2, 46, 0),
                            Likes = 235678,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "Feed Me Dope"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("21111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("21111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/super_slimey.jpg",
                            Length = new TimeSpan(0, 0, 3, 40, 0),
                            Likes = 98765,
                            ReleaseDate = new DateOnly(2017, 10, 20),
                            Title = "Killed Before"
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/pray_for_paris.jpg",
                            Length = new TimeSpan(0, 0, 1, 35, 0),
                            Likes = 123456,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "No Vacancy"
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/pray_for_paris.jpg",
                            Length = new TimeSpan(0, 0, 5, 49, 0),
                            Likes = 654321,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "327"
                        },
                        new
                        {
                            Id = new Guid("14111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/pray_for_paris.jpg",
                            Length = new TimeSpan(0, 0, 1, 49, 0),
                            Likes = 234567,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "Euro Step"
                        },
                        new
                        {
                            Id = new Guid("15111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("31111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("51111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/pray_for_paris.jpg",
                            Length = new TimeSpan(0, 0, 2, 4, 0),
                            Likes = 345678,
                            ReleaseDate = new DateOnly(2020, 4, 17),
                            Title = "Versace"
                        },
                        new
                        {
                            Id = new Guid("16111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/call_me_if_you_get_lost_the_estate_sale.jpg",
                            Length = new TimeSpan(0, 0, 2, 35, 0),
                            Likes = 456789,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "HOT WIND BLOWS"
                        },
                        new
                        {
                            Id = new Guid("17111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/call_me_if_you_get_lost_the_estate_sale.jpg",
                            Length = new TimeSpan(0, 0, 8, 35, 0),
                            Likes = 567890,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "WILSHIRE"
                        },
                        new
                        {
                            Id = new Guid("18111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/call_me_if_you_get_lost_the_estate_sale.jpg",
                            Length = new TimeSpan(0, 0, 2, 57, 0),
                            Likes = 678901,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "SAFARI"
                        },
                        new
                        {
                            Id = new Guid("19111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/call_me_if_you_get_lost_the_estate_sale.jpg",
                            Length = new TimeSpan(0, 0, 3, 36, 0),
                            Likes = 789012,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "WHAT A DAY"
                        },
                        new
                        {
                            Id = new Guid("20111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/call_me_if_you_get_lost_the_estate_sale.jpg",
                            Length = new TimeSpan(0, 0, 2, 41, 0),
                            Likes = 890123,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "DOGTOOTH"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("41111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/call_me_if_you_get_lost_the_estate_sale.jpg",
                            Length = new TimeSpan(0, 0, 3, 50, 0),
                            Likes = 901234,
                            ReleaseDate = new DateOnly(2023, 3, 31),
                            Title = "HEAVEN TO ME"
                        },
                        new
                        {
                            Id = new Guid("22111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/bane.jpg",
                            Length = new TimeSpan(0, 0, 2, 20, 0),
                            Likes = 12345,
                            ReleaseDate = new DateOnly(2019, 7, 30),
                            Title = "Bane"
                        },
                        new
                        {
                            Id = new Guid("23111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/if_looks_could_kill.jpg",
                            Length = new TimeSpan(0, 0, 3, 14, 0),
                            Likes = 23456,
                            ReleaseDate = new DateOnly(2023, 3, 3),
                            Title = "if looks could kill"
                        },
                        new
                        {
                            Id = new Guid("24111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/kat_food.jpg",
                            Length = new TimeSpan(0, 0, 4, 46, 0),
                            Likes = 34567,
                            ReleaseDate = new DateOnly(2023, 9, 1),
                            Title = "Kat Food"
                        },
                        new
                        {
                            Id = new Guid("25111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("31111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/xtended.jpg",
                            Length = new TimeSpan(0, 0, 3, 48, 0),
                            Likes = 45678,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "MDMA"
                        },
                        new
                        {
                            Id = new Guid("26111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/xtended.jpg",
                            Length = new TimeSpan(0, 0, 2, 18, 0),
                            Likes = 78901,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "Freestyle 2"
                        },
                        new
                        {
                            Id = new Guid("27111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("41111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/xtended.jpg",
                            Length = new TimeSpan(0, 0, 2, 45, 0),
                            Likes = 56789,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "Delinquent"
                        },
                        new
                        {
                            Id = new Guid("28111111-1111-1111-1111-111111111111"),
                            AlbumId = new Guid("51111111-1111-1111-1111-111111111111"),
                            CloudinaryPublicId = "",
                            GenreId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageURL = "/images/songs-art-covers/xtended.jpg",
                            Length = new TimeSpan(0, 0, 3, 21, 0),
                            Likes = 67890,
                            ReleaseDate = new DateOnly(2022, 10, 31),
                            Title = "Fashion Habits"
                        });
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "598bbcc9-7e30-4370-b24e-bfc4e8ac3edd",
                            Email = "kenCarson@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/ken_carson.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "kenCarson@gmail.com",
                            NormalizedUserName = "kenCarson",
                            PasswordHash = "AQAAAAIAAYagAAAAENOtUGIHSWMboFBUT0fgdbHhyVDTSOs7In0CTLr0lrwctp5uuijCv05nlxfDxF42Vw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "kenCarson"
                        },
                        new
                        {
                            Id = new Guid("02111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "09f13bc7-efa8-4b31-a672-3a09a817d1ab",
                            Email = "future@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/future.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "future@gmail.com",
                            NormalizedUserName = "future",
                            PasswordHash = "AQAAAAIAAYagAAAAEBwwKzagzaheS1WuqgBKzcoYl/iB/q9rP7UsFjD+L46bJVEzUb5p8ePsmrOsqU7uQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "future"
                        },
                        new
                        {
                            Id = new Guid("03111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "360dc326-7d8c-4a1a-846e-c22582eaa74d",
                            Email = "youngThug@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/young_thug.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "youngThug@gmail.com",
                            NormalizedUserName = "youngThug",
                            PasswordHash = "AQAAAAIAAYagAAAAEBA5aGS/3klVHRYZADehDmD8QUmoqwancV6dSzS3D2HOuG8y1r0Rcq+SzB0+po15+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "youngThug"
                        },
                        new
                        {
                            Id = new Guid("04111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d0602cf0-5d44-40fe-8b34-87978c92da64",
                            Email = "westsideGunn@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/westside_gunn.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "westsideGunn@gmail.com",
                            NormalizedUserName = "westsideGunn",
                            PasswordHash = "AQAAAAIAAYagAAAAEO6UVTFq45f/+vtMLC8FAt+iYI8Sfe5px1CVfclOl9LTQYeLTOh5a6iURdcSFcmRjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "westsideGunn"
                        },
                        new
                        {
                            Id = new Guid("05111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "89d0131c-e0fe-4468-b86a-f380ff6a7859",
                            Email = "tylerTheCreator@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/tyler_the_creator.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "tylerTheCreator@gmail.com",
                            NormalizedUserName = "tylerTheCreator",
                            PasswordHash = "AQAAAAIAAYagAAAAENi/wfW3GolVLNNeat4SmPBiIJeywtbMiP4nJEuofDdpho0mAONhVWFi61t+fSkbGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "05111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "tylerTheCreator"
                        },
                        new
                        {
                            Id = new Guid("06111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0ef6f9c-66b8-49a0-98a2-86cf177f5911",
                            Email = "destroyLonely@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/destroy_lonely.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "destroyLonely@gmail.com",
                            NormalizedUserName = "destroyLonely",
                            PasswordHash = "AQAAAAIAAYagAAAAEAk7RbmVRAmOpHRDXydpDhEUPgWjOLwZPmfI6tivhI5mwpSk/voGGFcDIOhkHohU6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "destroyLonely"
                        },
                        new
                        {
                            Id = new Guid("07111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75f9d8ae-5085-4759-86c7-4bddbe98f681",
                            Email = "joeyBada$$@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/joey_bada$$.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "joeyBada$$@gmail.com",
                            NormalizedUserName = "joeyBada$$",
                            PasswordHash = "AQAAAAIAAYagAAAAEEapdC+2wb3lS0lH3/ln3FCJb4NoWiM/fUimTSwBh31tTXST9iL/22JR0UPW8d/alA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "07111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "joeyBada$$"
                        },
                        new
                        {
                            Id = new Guid("08111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af459876-95c4-429b-9a96-d1bd9df12f80",
                            Email = "billiEssco@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/billie_essco.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "billiEssco@gmail.com",
                            NormalizedUserName = "billiEssco",
                            PasswordHash = "AQAAAAIAAYagAAAAEF9thttC+L0lk8on/vPR6QtXwoUNRsCgT8tdVGZiCon+EoSqgQ/Udh0eDqHuI5BN5g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "08111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "billiEssco"
                        },
                        new
                        {
                            Id = new Guid("09111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be145a31-a27e-4bba-90fc-233ad2284f84",
                            Email = "lilWayne@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/lil_wayne.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "lilWayne@gmail.com",
                            NormalizedUserName = "lilWayne",
                            PasswordHash = "AQAAAAIAAYagAAAAEGo1kAvCDG/YF6mozjMvbE1hPMVGxmYpIYRAtFT1jphuq65OLLGKf8AGucsCYYv3rw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "09111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "lilWayne"
                        },
                        new
                        {
                            Id = new Guid("10111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9cbff66-0c64-4ae6-80e4-5f55e5847db4",
                            Email = "homixideGang@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/homixide_gang.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "homixideGang@gmail.com",
                            NormalizedUserName = "homixideGang",
                            PasswordHash = "AQAAAAIAAYagAAAAEIDYe0sWTZL1N2zJGX5MtqbzgWKmEJ04pXw6ufUgeSUDmFfAxyje1Wf9zlVCxB0gWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "homixideGang"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd06fc8e-c0c9-4229-b01a-e8ce14f079bd",
                            Email = "stdimov2007@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/stasko456.JPG",
                            LockoutEnabled = false,
                            NormalizedEmail = "stdimov2007@gmail.com",
                            NormalizedUserName = "stasko456",
                            PasswordHash = "AQAAAAIAAYagAAAAEAACalutxpox1l7ZK4IpYp1qR4iXwP7IPt1c62RBKoBI/6UvlH9h/59UkBl9nF3mBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "11111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "stasko456"
                        },
                        new
                        {
                            Id = new Guid("12111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc1ce418-cb7b-494e-9a25-ab372619c519",
                            Email = "simon2403e8@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/simon333.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "simon2403e8@gmail.com",
                            NormalizedUserName = "simon333",
                            PasswordHash = "AQAAAAIAAYagAAAAEND4e80eYEr+yAgVkSP6SevGMFiDWjVW6cs1/PDTNxn2SdsdkfOw47mZIt/g4YULhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "simon333"
                        },
                        new
                        {
                            Id = new Guid("13111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43f5000a-f34a-483a-8a4c-d8e3f9a99431",
                            Email = "nikolaPeew@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/n_peew07.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "nikolaPeew@gmail.com",
                            NormalizedUserName = "n_peew07",
                            PasswordHash = "AQAAAAIAAYagAAAAEE3Wv8FHMefyKVgnaFNyc8nTrd5bnPKY4i+m0L7xttcJXCVE7CeJWP9YArGV8rwQow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "n_peew07"
                        },
                        new
                        {
                            Id = new Guid("14111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee20205c-9f05-4d17-a5a3-fb46ff798ed0",
                            Email = "gtonev@gmail.com",
                            EmailConfirmed = false,
                            ImageURL = "/images/users-pfps/gt_baby.jpg",
                            LockoutEnabled = false,
                            NormalizedEmail = "gtonev@gmail.com",
                            NormalizedUserName = "g_tonev",
                            PasswordHash = "AQAAAAIAAYagAAAAEGq2cbascFLngU3AzI22TiPeMzXtTYqcOXBOHvwMmKkE61b4mhXfUZ9sQu9ZJLnzyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "g_tonev"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Artist", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistAlbum", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Album", "Album")
                        .WithMany("ArtistsAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.Artist", "Artist")
                        .WithMany("ArtistsAlbums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.ArtistSong", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Artist", "Artist")
                        .WithMany("ArtistsSongs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.Song", "Song")
                        .WithMany("ArtistsSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.LikedSongs", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.User", "User")
                        .WithMany("LikedSongs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Playlist", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.PlaylistSong", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistsSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaskoFy.Models.Entities.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Song", b =>
                {
                    b.HasOne("StaskoFy.Models.Entities.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StaskoFy.Models.Entities.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Album", b =>
                {
                    b.Navigation("ArtistsAlbums");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Artist", b =>
                {
                    b.Navigation("ArtistsAlbums");

                    b.Navigation("ArtistsSongs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistsSongs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.Song", b =>
                {
                    b.Navigation("ArtistsSongs");

                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("StaskoFy.Models.Entities.User", b =>
                {
                    b.Navigation("LikedSongs");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
